### ISSUE TITLE
窗口显示问题

### ISSUE THREAD

**Issue by Coaixy** [zwy1234/bulletChat-Draw-Game#1]
系统：Windows11 21H2
Java：JDK17
[![h0rRs.png](https://s3.328888.xyz/2022/08/15/h0rRs.png)](https://imgloc.com/i/h0rRs)
[![h0qVp.png](https://s3.328888.xyz/2022/08/15/h0qVp.png)](https://imgloc.com/i/h0qVp)
遮挡和未完全显示

**Comment by zwy1234** [comment]
因为参数都写死了，所以会出现这种问题。可以试着把参数改成动态的，窗口总宽度和长度是自动获取的。

**Comment by Coaixy** [comment]
点击画板外也会上色
缩放窗口的时候画板会很奇怪
![)M14SEALAJW$TP)X%O~E)~P](https://user-images.githubusercontent.com/60541541/184623924-21a2c027-0d81-49c1-a18e-675c58ea8e4f.png)

**Comment by zwy1234** [comment]
没有做条件判断，因为原本没有鼠标点击上色功能的，主要还是通过直播间的弹幕命令来上色
